onEvent('jei.hide.items', event => {

const ItemHide = [
	//Coal (Ore, Dust)
		'minecraft:coal_ore',
		'silents_mechanisms:coal_dust',
		'mekanism:dust_coal',

	//Iron (Ore, Dust, Gear, Plate, Rod)
		'immersiveengineering:dust_iron',
		'silents_mechanisms:iron_dust',
		'mekanism:dust_iron',
		'mysticalworld:iron_dust',
		'thermal:iron_dust',
		'appliedenergistics2:iron_dust',
		'thermal:iron_gear',
		'titanium:iron_gear',
		'immersiveengineering:plate_iron',
		'thermal:iron_plate',
		'create:iron_sheet',
		'silentgear:iron_rod',
		'immersiveengineering:stick_iron',
		'buildersaddition:iron_rod',
		'createaddition:iron_rod',
		'minecraft:iron_ore',

	//Gold (Ore, Dust, Gear, Plate, Rod)
		'immersiveengineering:dust_gold',
		'silents_mechanisms:gold_dust',
		'mekanism:dust_gold',
		'mysticalworld:gold_dust',
		'thermal:gold_dust',
		'thermal:gold_gear',
		'titanium:gold_gear',
		'thermal:gold_plate',
		'immersiveengineering:plate_gold',
		'immersiveposts:stick_gold',
		'createaddition:gold_rod',
		'minecraft:gold_ore',
		'minecraft:nether_gold_ore',

	//Diamond (Ore, Dust, Gear)
		'createaddition:diamond_grit',
		'mekanism:dust_diamond',
		'thermal:diamond_dust',
		'thermal:diamond_gear',
		'titanium:diamond_gear',
		'minecraft:diamond_ore',

	//Emerald (Ore, Dust, Gear)
		'mekanism:dust_emerald',
		'thermal:emerald_dust',
		'thermal:emerald_gear',
		'minecraft:emerald_ore',

	//Lapis Lazuli (Ore, Dust, Gear, Plate)
		'thermal:lapis_dust',
		'mekanism:dust_lapis_lazuli',
		'thermal:lapis_lazuli_gear',
		'create:lapis_sheet',
		'minecraft:lapis_ore',

	//Nether Quartz (Ore, Dust, Gear)
		'mekanism:dust_quartz',
		'thermal:quartz_dust',
		'thermal:quartz_gear',
		'minecraft:nether_quartz_ore',

	//Copper (Ore, Ingot, Block, Nugget, Dust, Gear, Plate, Rod)
		'silents_mechanisms:copper_ingot',
		'tmechworks:copper_ingot',
		'mekanism:ingot_copper',
		'mysticalworld:copper_ingot',
		'thermal:copper_ingot',
		'immersiveengineering:ingot_copper',
		'create:copper_ingot',
		'tconstruct:copper_ingot',
		'projectred-core:copper_ingot',
		'silents_mechanisms:copper_block',
		'tmechworks:copper_block',
		'mekanism:block_copper',
		'mysticalworld:copper_block',
		'thermal:copper_block',
		'immersiveengineering:storage_copper',
		'create:copper_block',
		'tconstruct:copper_block',
		'silents_mechanisms:copper_nugget',
		'tmechworks:copper_nugget',
		'mekanism:nugget_copper',
		'mysticalworld:copper_nugget',
		'thermal:copper_nugget',
		'immersiveengineering:nugget_copper',
		'occultism:copper_nugget',
		'create:copper_nugget',
		'tconstruct:copper_nugget',
		'immersiveengineering:dust_copper',
		'silents_mechanisms:copper_dust',
		'mekanism:dust_copper',
		'mysticalworld:copper_dust',
		'thermal:copper_dust',
		'thermal:copper_gear',
		'create:copper_sheet',
		'thermal:copper_plate',
		'immersiveengineering:plate_copper',
		'immersiveposts:stick_copper',
		'createaddition:copper_rod',
		'immersiveengineering:ore_copper',
		'mekanism:copper_ore',
		'create:copper_ore',
		'thermal:copper_ore',
		'tmechworks:copper_ore',
		'mysticalworld:copper_ore',
		'silents_mechanisms:copper_ore',
		'tconstruct:copper_ore',
		'projectred-exploration:copper_ore',
		'bno:copper_ingot',
		'bno:copper_nugget',
		'bno:copper_block',
		'projectred-exploration:copper_block',

	//Aluminium (Ore, Ingot, Block, Nugget, Dust, Plate, Rod)
		'silents_mechanisms:aluminum_ingot',
		'tmechworks:aluminum_ingot',
		'immersiveengineering:ingot_aluminium',
		'silents_mechanisms:aluminum_block',
		'tmechworks:aluminum_block',
		'immersiveengineering:storage_aluminium',
		'silents_mechanisms:aluminum_nugget',
		'tmechworks:aluminum_nugget',
		'immersiveengineering:nugget_aluminium',
		'silents_mechanisms:aluminum_dust',
		'immersiveengineering:dust_aluminium',
		'immersiveengineering:plate_aluminium',
		'immersiveengineering:stick_aluminium',
		'tmechworks:aluminum_ore',
		'immersiveengineering:ore_aluminum',
		'silents_mechanisms:bauxite_ore',
		'bno:aluminum_block',

	//Silver (Ore, Ingot, Block, Nugget, Plate, Gear, Rod)
		'silents_mechanisms:silver_ingot',
		'mysticalworld:silver_ingot',
		'thermal:silver_ingot',
		'immersiveengineering:ingot_silver',
		'projectred-core:silver_ingot',
		'silents_mechanisms:silver_block',
		'mysticalworld:silver_block',
		'thermal:silver_block',
		'immersiveengineering:storage_silver',
		'silents_mechanisms:silver_nugget',
		'mysticalworld:silver_nugget',
		'thermal:silver_nugget',
		'immersiveengineering:nugget_silver',
		'silents_mechanisms:silver_dust',
		'mysticalworld:silver_dust',
		'thermal:silver_dust',
		'immersiveengineering:dust_silver',
		'thermal:silver_gear',
		'thermal:silver_plate',
		'immersiveengineering:plate_silver',
		'immersiveposts:stick_silver',
		'immersiveengineering:ore_silver',
		'thermal:silver_ore',
		'mysticalworld:silver_ore',
		'silents_mechanisms:silver_ore',
		'projectred-exploration:silver_ore',
		'bno:silver_ingot',
		'bno:silver_nugget',
		'bno:silver_block',
		'projectred-exploration:silver_block',

	//Lead (Ore, Ingot, Dust, Plate, Gear, Rod, Nugget)
		'silents_mechanisms:lead_ingot',
		'mekanism:ingot_lead',
		'mysticalworld:lead_ingot',
		'thermal:lead_ingot',
		'immersiveengineering:ingot_lead',
		'silents_mechanisms:lead_block',
		'mekanism:block_lead',
		'mysticalworld:lead_block',
		'thermal:lead_block',
		'immersiveengineering:storage_lead',
		'silents_mechanisms:lead_nugget',
		'mekanism:nugget_lead',
		'mysticalworld:lead_nugget',
		'thermal:lead_nugget',
		'immersiveengineering:nugget_lead',
		'silents_mechanisms:lead_dust',
		'mekanism:dust_lead',
		'mysticalworld:lead_dust',
		'thermal:lead_dust',
		'immersiveengineering:dust_lead',
		'thermal:lead_gear',
		'thermal:lead_plate',
		'immersiveengineering:plate_lead',
		'immersiveposts:stick_lead',
		'immersiveengineering:ore_lead',
		'mekanism:lead_ore',
		'thermal:lead_ore',
		'mysticalworld:lead_ore',
		'silents_mechanisms:lead_ore',
		'bno:lead_ingot',
		'bno:lead_nugget',
		'bno:lead_block',

	//Nickel (Ingot, Block, Nugget, Dust, Gear, Plate, Rod)
		'silents_mechanisms:nickel_ingot',
		'thermal:nickel_ingot',
		'immersiveengineering:ingot_nickel',
		'silents_mechanisms:nickel_block',
		'thermal:nickel_block',
		'immersiveengineering:storage_nickel',
		'silents_mechanisms:nickel_nugget',
		'thermal:nickel_nugget',
		'immersiveengineering:nugget_nickel',
		'silents_mechanisms:nickel_dust',
		'thermal:nickel_dust',
		'immersiveengineering:dust_nickel',
		'thermal:nickel_gear',
		'thermal:nickel_plate',
		'immersiveengineering:plate_nickel',
		'immersiveposts:stick_nickel',
		'immersiveengineering:ore_nickel',
		'thermal:nickel_ore',
		'silents_mechanisms:nickel_ore',
		'bno:nickel_nugget',
		'bno:nickel_ingot',
		'bno:nickel_block',

	//Uranium (Ingot, Block, Nugget, Dust, Plate, Post, Ore)
		'silents_mechanisms:uranium_ingot',
		'mekanism:ingot_uranium',
		'immersiveengineering:ingot_uranium',
		'silents_mechanisms:uranium_block',
		'mekanism:block_uranium',
		'immersiveengineering:storage_uranium',
		'silents_mechanisms:uranium_nugget',
		'mekanism:nugget_uranium',
		'immersiveengineering:nugget_uranium',
		'silents_mechanisms:uranium_dust',
		'mekanism:dust_uranium',
		'immersiveengineering:dust_uranium',
		'immersiveengineering:plate_uranium',
		'immersiveposts:stick_uranium',
		'immersiveengineering:ore_uranium',
		'mekanism:uranium_ore',
		'silents_mechanisms:uranium',
		'bno:uranium_ingot',
		'bno:uranium_block',

	//Osmium (Ingot, Block, Nugget, Dust, Ore)
		'mekanism:ingot_osmium',
		'mekanism:block_osmium',
		'mekanism:nugget_osmium',
		'mekanism:dust_osmium',
		'mekanism:osmium_ore',
		'bno:osmium_nugget',
		'bno:osmium_ingot',
		'bno:osmium_block',

	//Tin (Ingot, Block, Nugget, Gear, Plate, Ore)
		'silents_mechanisms:tin_ingot',
		'mekanism:ingot_tin',
		'mysticalworld:tin_ingot',
		'thermal:tin_ingot',
		'projectred-core:tin_ingot',
		'bno:tin_ingot',
		'silents_mechanisms:tin_block',
		'mekanism:block_tin',
		'mysticalworld:tin_block',
		'thermal:tin_block',
		'silents_mechanisms:tin_nugget',
		'mekanism:nugget_tin',
		'mysticalworld:tin_nugget',
		'thermal:tin_nugget',
		'silents_mechanisms:tin_dust',
		'mekanism:dust_tin',
		'mysticalworld:tin_dust',
		'thermal:tin_dust',
		'thermal:tin_gear',
		'thermal:tin_plate',
		'mekanism:tin_ore',
		'thermal:tin_ore',
		'mysticalworld:tin_ore',
		'silents_mechanisms:tin_ore',
		'projectred-exploration:tin_ore',
		'bno:tin_nugget',
		'bno:tin_block',
		'projectred-exploration:tin_block',

	//Zinc (Ingot, Block, Nugget, Dust, Plate, Ore)
		'silents_mechanisms:zinc_ingot',
		'create:zinc_ingot',
		'silents_mechanisms:zinc_block',
		'create:zinc_block',
		'silents_mechanisms:zinc_nugget',
		'create:zinc_nugget',
		'silents_mechanisms:zinc_dust',
		'createaddition:zinc_sheet',
		'create:zinc_ore',
		'silents_mechanisms:zin_ore',

	//Cobalt (Ingot, Block, Nugget, Ore)
		'tconstruct:cobalt_ingot',
		'tconstruct:cobalt_block',
		'tconstruct:cobalt_nugget',
		'tconstruct:cobalt_ore',

	//Flourite (Crystal, Dust, Ore)
		'mekanism:fluorite_gem',
		'mekanism:dust_fuorite',
		'mekanism:fluorite_ore',

	//Bitumen (Gem, Block)
		'immersivepetroleum:bitumen',
		'thermal:bitumen',
		'thermal:bitumen_block',

	//Cinnabar (Gem, Block, Dust, Ore)
		'thermal:cinnabar',
		'thermal:cinnabar_block',
		'thermal:cinnabar_dust',
		'thermal:cinnabar_ore',

	//Apatite (Gem, Block, Dust, Ore)
		'thermal:apatite',
		'thermal:apatite_block',
		'thermal:apatite_dust',
		'thermal:apatite_ore',

	//Sulfur (Gem, Block, Dust, Ore)
		'thermal:sulfur',
		'thermal:sulfur_block',
		'thermal:sulfur_dust',
		'immersiveengineering:dust_sulfur',
		'mekanism:dust_sulfur',
		'thermal:sulfur_ore',

	//Potassium Nitrate (Gem, Block, Dust)
		'thermal:niter',
		'thermal:niter_block',
		'thermal:niter_dust',

	//Bronze (Ingot, Block, Nugget, Dust, Gear, Plate)
		'silents_mechanisms:bronze_ingot',
		'mekanism:ingot_bronze',
		'thermal:bronze_ingot',
		'silents_mechanisms:bronze_block',
		'mekanism:block_bronze',
		'thermal:bronze_block',
		'silents_mechanisms:bronze_nugget',
		'mekanism:nugget_bronze',
		'thermal:bronze_nugget',
		'silents_mechanisms:bronze_dust',
		'mekanism:dust_bronze',
		'thermal:bronze_gear',
		'thermal:bronze_plate',

	//Brass (Ingot, Block, Nugget, Dust, Plate, Rod)
		'silents_mechanisms:brass_ingot',
		'create:brass_ingot',
		'silents_mechanisms:brass_block',
		'create:brass_block',
		'silents_mechanisms:brass_nugget',
		'create:brass_nugget',
		'silents_mechanisms:brass_dust',
		'create:brass_sheet',
		'createaddition:brass_rod',

	//Electrum (Ingot, Block, Nugget, Dust, Gear, Plate, Rod)
		'silents_mechanisms:electrum_ingot',
		'thermal:electrum_ingot',
		'immersiveengineering:ingot_electrum',
		'silents_mechanisms:electrum_block',
		'thermal:electrum_block',
		'immersiveengineering:storage_electrum',
		'silents_mechanisms:electrum_nugget',
		'thermal:electrum_nugget',
		'immersiveengineering:nugget_electrum',
		'silents_mechanisms:electrum_dust',
		'immersiveengineering:dust_electrum',
		'thermal:electrum_gear',
		'thermal:electrum_plate',
		'immersiveengineering:plate_electrum',
		'immersiveposts:stick_electrum',

	//Constantan (Ingot, Block, Nugget, Dust, Gear, Plate, Rod)
		'thermal:constantan_ingot',
		'immersiveengineering:ingot_constantan',
		'thermal:constantan_block',
		'immersiveengineering:storage_constantan',
		'thermal:constantan_nugget',
		'immersiveengineering:nugget_constantan',
		'immersiveengineering:dust_constantan',
		'thermal:constantan_gear',
		'thermal:constantan_plate',
		'immersiveengineering:plate_constantan',
		'immersiveposts:stick_constantan',

	//Steel (Ingot, Block, Nugget, Dust, Plate, Rod)
		'silents_mechanisms:steel_ingot',
		'mekanism:ingot_steel',
		'assemblylinemachines:steel_ingot',
		'immersiveengineering:ingot_steel',
		'silents_mechanisms:steel_block',
		'mekanism:block_steel',
		'assemblylinemachines:steel_block',
		'immersiveengineering:storage_steel',
		'silents_mechanisms:steel_nugget',
		'mekanism:nugget_steel',
		'assemblylinemachines:steel_nugget',
		'immersiveengineering:nugget_steel',
		'silents_mechanisms:steel_dust',
		'mekanism:dust_steel',
		'immersiveengineering:dust_steel',
		'immersiveengineering:plate_steel',
		'immersiveengineering:stick_steel',

	//Invar (Ingot, Block, Nugget, Dust, Gear, Plate)
		'silents_mechanisms:invar_ingot',
		'thermal:invar_ingot',
		'silents_mechanisms:invar_block',
		'thermal:invar_block',
		'silents_mechanisms:invar_nugget',
		'thermal:invar_nugget',
		'silents_mechanisms:invar_dust',
		'thermal:invar_gear',
		'thermal:invar_plate',

	//Lumium (Ingot, Block, Nugget, Dust, Gear, Plate)
		'silents_mechanisms:lumium_ingot',
		'thermal:lumium_ingot',
		'silents_mechanisms:lumium_block',
		'thermal:lumium_block',
		'silents_mechanisms:lumium_nugget',
		'thermal:lumium_nugget',
		'silents_mechanisms:lumium_dust',
		'thermal:lumium_gear',
		'thermal:lumium_plate',

	//Signalum (Ingot, Block, Nugget, Dust, Gear, Plate)
		'silents_mechanisms:signalum_ingot',
		'thermal:signalum_ingot',
		'silents_mechanisms:signalum_block',
		'thermal:signalum_block',
		'silents_mechanisms:signalum_nugget',
		'thermal:signalum_nugget',
		'silents_mechanisms:signalum_dust',
		'thermal:signalum_gear',
		'thermal:signalum_plate',
		'bno:aluminum_ingot',
		'bno:aluminum_nugget',

	//Enderium (Ingot, Block, Nugget, Dust, Gear, Plate)
		'silents_mechanisms:enderium_ingot',
		'thermal:enderium_ingot',
		'silents_mechanisms:enderium_block',
		'thermal:enderium_block',
		'silents_mechanisms:enderium_nugget',
		'thermal:enderium_nugget',
		'silents_mechanisms:enderium_dust',
		'thermal:enderium_gear',
		'thermal:enderium_plate',

	//Silicon (Gem)
		'refinedstorage:silicon',

	//Coal Coke (Gem, Block, Dust)
		'immersiveengineering:coal_coke',
		'thermal:coal_coke',
		'immersiveengineering:coke',
		'thermal:coal_coke_block',
		'immersiveengineering:dust_coke',

	//Charcoal (Dust)
		'mekanism:dust_charcoal',

	//Others
		'minecraft:redstone_ore',

	];
    ItemHide.forEach((hide) => {
        event.hide(hide);
    });

});